---
- hosts: all

  vars:
    distro_nicks:
      "CentOS": centos
      "Red Hat Enterprise Linux": rhel
    distro_nick: "{{ distro_nicks[ansible_distribution] }}"

    ssg_profile_id: xccdf_org.ssgproject.content_profile_standard

    package_list:
      - openscap-scanner
      - scap-security-guide

    output_variable_list:
      - example
      - rhel_N_profiles
      - centos_N_profiles
      - rhel_N_evaluation
      - centos_N_evaluation
      - existing_rhel_ds_xml_files
      - existing_centos_ds_xml_files

    output_extension_list:
      - json
      - stdout
      - stderr

    remote: /home/vagrant
    local: /vagrant
    out: "{{ local }}/out/{{ inventory_hostname_short }}"
    reports: "{{ local }}/reports/{{ inventory_hostname_short }}"

  tasks:
    - name: local setup
      become: yes
      block:
        - name: local directories
          loop:
            - "{{ out }}"
            - "{{ reports }}"
          loop_control:
            label: "{{ item }}"
          file:
            state: directory
            path: "{{ item }}"

    - name: system configuration changes that might require a reboot
      become: yes
      block:
        - name: selinux targeted enforcing
          selinux:
            policy: targeted
            state: enforcing
          register: selinux_status
        - name: reboot if necessary
          when: selinux_status.reboot_required
          reboot:

    - name: system configuration changes
      become: yes
      block:
        - name: packages
          package:
            name: "{{ package_list }}"
            state: present

    - name: openscap for centos
      become: no
      block:
        - name: existing rhel?-ds.xml files
          find:
            use_regex: yes
            file_type: file
            paths:
              - /usr/share/xml/scap/ssg/content
            patterns:
              - ssg-rhel\d+-ds\.xml
          register: existing_rhel_ds_xml_files
        - name: existing centos?-ds.xml files
          find:
            use_regex: yes
            file_type: file
            paths:
              - /usr/share/xml/scap/ssg/content
            patterns:
              - ssg-centos\d+-ds\.xml
          register: existing_centos_ds_xml_files

    - name: oscap scanner tests
      become: no
      block:
        - name: example
          # https://www.open-scap.org/getting-started/
          command:
            argv:
              - oscap
              - info
              - /usr/share/xml/scap/ssg/content/ssg-rhel6-ds.xml
          register: example
          ignore_errors: yes
        - name: "rhel {{ ansible_distribution_major_version }} profiles"
          command:
            argv:
              - oscap
              - info
              - --fetch-remote-resources
              - "/usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml"
          register: rhel_N_profiles
          ignore_errors: yes
        - name: "centos {{ ansible_distribution_major_version }} profiles"
          command:
            argv:
              - oscap
              - info
              - --fetch-remote-resources
              - "/usr/share/xml/scap/ssg/content/ssg-centos{{ ansible_distribution_major_version }}-ds.xml"
          register: centos_N_profiles
          ignore_errors: yes
        - name: "rhel {{ ansible_distribution_major_version }} evaluation"
          become: yes
          command:
            argv:
              - oscap
              - xccdf
              - eval
              - --fetch-remote-resources
              - --cpe
              - "/usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-cpe-dictionary.xml"
              - --profile
              - "{{ ssg_profile_id }}"
              - --results-arf
              - "{{ reports }}/rhel_{{ ansible_distribution_major_version }}_evaluation.arf.xml"
              - --report
              - "{{ reports }}/rhel_{{ ansible_distribution_major_version }}_evaluation.report.html"
              - "/usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-ds.xml"
          register: rhel_N_evaluation
          ignore_errors: yes
        - name: "centos {{ ansible_distribution_major_version }} evaluation"
          become: yes
          command:
            argv:
              - oscap
              - xccdf
              - eval
              - --fetch-remote-resources
              - --cpe
              - "/usr/share/xml/scap/ssg/content/ssg-rhel{{ ansible_distribution_major_version }}-cpe-dictionary.xml"
              - --profile
              - "{{ ssg_profile_id }}"
              - --results-arf
              - "{{ reports }}/centos_{{ ansible_distribution_major_version }}_evaluation.arf.xml"
              - --report
              - "{{ reports }}/centos_{{ ansible_distribution_major_version }}_evaluation.report.html"
              - "/usr/share/xml/scap/ssg/content/ssg-centos{{ ansible_distribution_major_version }}-ds.xml"
          register: centos_N_evaluation
          ignore_errors: yes

      always:
        - name: copy selinux bug workaround
          when: >-
            ansible_selinux.status == 'enabled'
            and ansible_python.version.major == 3
          loop: "{{ output_variable_list | product(output_extension_list) | list }}"
          loop_control:
            label: "{{ out }}/{{ item.0 }}.{{ item.1 }}"
          file:
            path: "{{ out }}/{{ item.0 }}.{{ item.1 }}"
            state: touch
        - name: variable json
          loop: "{{ output_variable_list }}"
          loop_control:
            label: "{{ out }}/{{ item }}.json"
          copy:
            dest: "{{ out }}/{{ item }}.json"
            content: "{{ lookup('vars', item) | to_nice_json }}"
        - name: variable output
          loop: "{{ output_variable_list | product(['stdout','stderr']) | list }}"
          loop_control:
            label: "{{ out }}/{{ item.0 }}.{{ item.1 }}"
          copy:
            dest: "{{ out }}/{{ item.0 }}.{{ item.1 }}"
            content: "{{ lookup('vars', item.0)[item.1] }}"
          when: item.1 in lookup('vars', item.0)
